name: MLflow CI

on:
  push:
    branches: ["main"]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn joblib pandas

      # 4. Debug semua file (penting)
      - name: Show project structure
        run: ls -R

      # 5. FORCE HAPUS conda_env (biar gak error lagi)
      - name: Remove conda_env from MLproject
        run: |
          if [ -f MLproject ]; then
            sed -i '/conda_env/d' MLproject
          fi

      # 6. Tampilkan isi MLproject
      - name: Show MLproject
        run: cat MLproject

      # 7. Jalankan MLflow Project
      - name: Run MLflow Project
        run: mlflow run .