name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn joblib pandas

      # 4. Debug (optional tapi bagus)
      - name: Show project structure
        run: ls -R

      # 5. Prepare folder (ANTI ERROR CI)
      - name: Prepare directories
        run: |
          mkdir -p artifacts

      # 6. Run MLflow Project (FIX UTAMA)
      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_URI: sqlite:///mlflow.db
          MLFLOW_ARTIFACT_URI: ./artifacts
        run: |
          mlflow run . --env-manager=local

      # 7. Upload hasil (BEST PRACTICE)
      - name: Upload MLflow results
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results
          path: |
            mlflow.db
            artifacts/